services:
  - type: web
    name: docugenv1
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: FLASK_ENV
        value: development